const FRAME_COLORS = {
  'Matte Black',
  'Space Gray',
  'Rose Gold',
  'Clearly White',
  'Just Black',
  'Not Pink',
  'Silver Titanium',
  'Arctic Silver',
  'Coral Blue',
  'Maple Gold',
  'Midnight Black',
  'Midnight Green',
  'Orchid Gray',
  'Burgundy Red',
  'Lilac Purple',
  'Sunrise Gold',
  'Titanium Gray',
  'Flamingo Pink',
  'Prism Black',
  'Prism Blue',
  'Prism Green',
  'Prism White',
  'Ceramic White',
  'Oh So Orange',
  'Aura Black',
  'Aura Glow',
  'Aura Pink',
  'Aura Red',
  'Aura White',
  'Aura Blue',
  'Coral',
  'Black',
  'White',
  'Gold',
  'Silver',
  'Blue',
  'Red',
  'Yellow',
  'Green',
  'Pink',
  'Purple',
};
